Dev vova
JlPOCTO/YaHack pull request #13
Opened 2024-04-13 11:21 UTC by JlPOCTO

2024-04-13 12:06 UTC, ElviraMinko approved these changes, later dismissed

2024-04-14 01:36 UTC, gr33n-m1ner requested changes
В целом очень круто, большая работа проделана

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/createAllDBs.js
> +})();
Добавить пустую строку в конце
Лучше переименовать файл в createDB, мы же создаем только 1 базу данных, и перенести в папку database

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/db.js
Я бы переименовал в launchDB

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	const res = await db.get(`SELECT message, time, fromID, IMGPath FROM MessageDB WHERE chatID = ${chatID} ORDER BY time`);
IMGPath поменял бы на imagePath, не экономь на буквах

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +		for (let user of users) {
Если тип чата direct, то оставь название null или пустой строкой
Название личного чата у каждого пользователя свое, а не конкатенация имен двух пользователей

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	name += "AUTO";
Для чего это нужно?

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	const res = await db.get(`INSERT INTO ChatsDB(name, pathToIMG, type)\
pathToIMG лучше переименовать в avatarPath, кажется это более осмысленное название

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	VALUES(\"${name}\", \"\", \"${type}\")\
Эти \\" нужны, чтобы нельзя было сломать таблицу плохими данными?
Для type экранирование не нужно, это enum, который мы сами контролируем. В будущем, если важно, в routes добавим проверку на корректность type, и будем возвращать код ответа с ошибкой, если там что-либо кроме direct и group

Еще желательно отформатировать, потому что очень тяжело читается

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	if (res !== undefined) {
Я бы не присваивал newID значение (т.е. оно бы имело значение undefined)
Здесь (res !== undefined) заменил бы на (res), т.к. undefined кастится к false
И дальше (newID != -1) заменил на (newID)

Если же ты против такой смены, то просто поменяй newID != -1 на newID !== -1

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	const res = await db.get(`SELECT chats.chatID, chats.name
Возвращай все значения из chats. Для корректного отображения нужен еще тип чата и ссылка на аватар
Ужасный нейминг cuBD, смени на chatsUsers

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +async function addMessage(db, chatID, fromID, message, time, IMGPath) {
IMGPath -> imagePath

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	await dbCreate.checkDB("./DB/sqlite.db", "MessageDB", "(\
Странно, что везде названия ChatsDB ChatsUsersDB, но почему-то Message в единственном числе. Я бы в целом все таблицы называл в единственном числе, но это кажется уже доеб из ничего, поэтому оставляю на твое усмотрение

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	await dbCreate.checkDB("./DB/sqlite.db", "MessageDB", "(\
На всякий случай я бы добавил сообщениям поле id

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +		type VARCHAR(\
Странный перенос
Еще возвращаясь к безопасности можно добавить такую штуку
type TEXT CHECK(type IN ('direct', 'group'))

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbCreate.js
Файл и название функции лучше переименовать в checkOrCreateTable
Но кажется открытие базы данных здесь это устаревший не работающий код? И тогда функция и файл это просто createTable
В названиях аргументов не нужен префикс db, то что они связаны с db очевидно из контекста
dbPath в будущем думаю стоит убрать, так как у нас будет всего одна база данных, а ее расположение лучше будет вынести в файл .env. Можешь пока этим не заниматься, я сделаю это сам в будущем

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbUsers.js
> +async function addUser(db, userID, userName, userNickname) {
Префикс user лишний, очевидно из контекста чьи это данные
Nickname -> login, чтобы согласовывалось с логикой названий из таблицы

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbUsers.js
> +    const IMGPath = "";
IMGPath -> avatarPath

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbUsers.js
> +//а надо ли?...
Стоит оставить для удаления плохих данных во время тестирования. Комментарий убрать

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbUsers.js
> +    if (res === undefined) return "";
Почему здесь возвращается пустая строка? res вроде должно быть типа массива? Даже если "" автоматически скаститься в [], лучше поменяй для лучшей читаемости

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbUsers.js
> +    if (res === undefined) return "";
Почему здесь возвращается пустая строка
userID -> id
Возможно мы хотим возвращать больше информации о пользователе, как минимум я не понимаю, почему эта функция возвращает больше данных, чем findByNickname

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbUsers.js
> +async function findByNickname(db, nickname) {
findByLogin

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbUsers.js
> +		avatarIMGPath VARCHAR(255)\
avatarPath

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/routes.js
> +    version + '/dialogs',
Метод называется dialogs, хотя возвращает только 1 диалог
В целом корректнее назвать /chat, потому что диалог означает разговор между двумя людьми, т.е. подразумевает тип чата direct, а метод может возвращать и групповые чаты

Это лучше обговорить с Элей, но здесь нужна реализация, которая принимает chatID не в query, а другим образом, что-то типо
/chat/:chatID
А внутри req.params.chatID

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/routes.js
> +    version + '/dialogs',
Только в конце заметил, что у тебя нарушена логика метода. Чтобы получить чаты, мы используем userID, а не chatID
Метод все же /chats
Так же надо подумать, нужен ли нам метод, который возвращает чат по userId и chatId (мне кажется, что нет)

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/routes.js
> +    version + '/createChat',
create лишнее. Из семантики метода post следует, что мы будем создавать что-то новое

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/routes.js
> +        res.send(dbChats.addChat(db, [req.query.userIDs], req.query.chatType, req.query.chatName));
Для чего userIDs обернуты в массив?

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/routes.js
> +    version + '/myInfo',
Я бы переименовал в /profile

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/routes.js
> +        const dialogID = req.query.dialogID;
dialogID -> chatID

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/routes.js
> +    version + '/addMessage',
addMessage -> message
По той же причине, что и до этого

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/routes.js
> +        const dialogID = req.query.dialogID;
chatID

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/routes.js
> +        dbChats.addMessage(db, dialogID, fromID, message, time, IMGPath);
Лучше все переменные сразу вставить в функцию, типо
dbChats.addMessage(db, 
    req.query.dialogID, 
    req.query.fromID, 
    ...
);

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/strategies/github.js
> +const dbUsers = require('../database/dbUsers');
Можно импортировать только одну конкретную функцию, типо
{addUser} = require('../database/dbUsers');

Это применимо ко многим местам, я только в конце об этом подумал. Можешь поискать остальные места и тоже поисправлять

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/database/dbCreate.js
>      await db.exec("CREATE TABLE IF NOT EXISTS " + dbName + " " + params);
Думаю лучше заменить "..." + name  + ".." на `... ${name} ...`

2024-04-14 01:36 UTC, gr33n-m1ner commented on server/src/strategies/github.js
> +        dbUsers.addUser(db, profile.id, profile.displayName, profile.username)
Здесь и в некоторых других местах ide дает предупреждение о том, что результат promise игнорируется
Гугл говорит, что есть такие решения 
1. Использование .catch() для обработки ошибок - на будущее хороший вариант, потому что стоит о таком подумать
2. Использование .then() без обработчика результата - выглядит костыльно, но мне кажется в целом норм

2024-04-14 21:05 UTC, JlPOCTO commented on server/src/database/dbChats.js
> +	const res = await db.get(`SELECT message, time, fromID, IMGPath FROM MessageDB WHERE chatID = ${chatID} ORDER BY time`);
мне лично визуальнее приятнее именно сокращение IMG

2024-04-14 21:07 UTC, JlPOCTO commented on server/src/database/dbChats.js
> +	name += "AUTO";
это нужно было раньше, когда типов чата не было, для "определения" этого самого типа) сейчас да, лишнее

2024-04-14 21:09 UTC, JlPOCTO commented on server/src/routes.js
> +        dbChats.addMessage(db, dialogID, fromID, message, time, IMGPath);
я думал над этим, но решил оставить в переменных, чтобы если что было удобнее как-то обрабатывать параметры

2024-04-14 21:11 UTC, JlPOCTO commented on server/src/strategies/github.js
> +        dbUsers.addUser(db, profile.id, profile.displayName, profile.username)
все проще, я забыл await

2024-04-14 21:22 UTC, JlPOCTO commented on server/src/database/dbChats.js
> +	VALUES(\"${name}\", \"\", \"${type}\")\
Нет такой вещи, как enum в sqlite
Для строк нужны кавычки

2024-04-14 21:23 UTC, JlPOCTO commented on server/src/database/dbChats.js
> +	VALUES(\"${name}\", \"\", \"${type}\")\
И да, я забыл что внутри обратный кавычек можно не экранировать

2024-04-14 21:28 UTC, JlPOCTO commented on server/src/database/dbChats.js
> +async function addMessage(db, chatID, fromID, message, time, IMGPath) {
IMGPath

2024-04-14 21:29 UTC, JlPOCTO commented on server/src/database/dbChats.js
> +	await dbCreate.checkDB("./DB/sqlite.db", "MessageDB", "(\
они по умолчанию есть, id

2024-04-14 21:31 UTC, gr33n-m1ner commented on server/src/createAllDBs.js
> +})();
Почему ты считаешь, что название launchDB предпочтительнее? Мы же ее именно что создаем, а не запускаем. Запускает базу данных db.js

2024-04-14 21:33 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	const res = await db.get(`SELECT message, time, fromID, IMGPath FROM MessageDB WHERE chatID = ${chatID} ORDER BY time`);
Окей, но я в корне с тобой не согласен, потому что такое название также противоречит camelCase-у, а мы вроде в нем пишем (Названия классов начинаются с большой буквы, названия переменных с маленькой, т.е. imgPath)

2024-04-14 21:34 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	name += "AUTO";
Если лишнее, то нужно убрать

2024-04-14 21:35 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	VALUES(\"${name}\", \"\", \"${type}\")\
> Нет такой вещи, как enum в sqlite Для строк нужны кавычки

Я нашел что-то, похожее на enum, там дальше в замечаниях

2024-04-14 21:36 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	VALUES(\"${name}\", \"\", \"${type}\")\
> И да, я забыл что внутри обратный кавычек можно не экранировать

Тогда эти экранирования лишние? Стоит убрать

2024-04-14 21:39 UTC, JlPOCTO commented on server/src/database/dbUsers.js
> +async function addUser(db, userID, userName, userNickname) {
Нет, если ты будешь работать откуда-то, где одновременно будут userID и chatID, то можно запутаться. Поэтому считаю префиксы уместными

2024-04-14 21:41 UTC, gr33n-m1ner commented on server/src/routes.js
> +        dbChats.addMessage(db, dialogID, fromID, message, time, IMGPath);
Хорошо, если не придумаем, как и что обрабатывать, то уберем в будущем

2024-04-14 21:42 UTC, JlPOCTO commented on server/src/routes.js
> +    version + '/dialogs',
вот поэтому и нужны префиксы в функциях, чтобы в подсказках замечать такие баги

2024-04-14 21:43 UTC, JlPOCTO commented on server/src/routes.js
> +    version + '/createChat',
не надо лишнее постоянно убирать! Мы потом запутаемся, какой именно запрос делаем

2024-04-14 21:43 UTC, JlPOCTO commented on server/src/routes.js
> +    version + '/createChat',
Что ж ты так префиксы не любишь

2024-04-14 21:44 UTC, gr33n-m1ner commented on server/src/database/dbChats.js
> +	await dbCreate.checkDB("./DB/sqlite.db", "MessageDB", "(\
Зачем тогда в ChatsDB хранить chatID и в UsersDB хранить userID?

2024-04-14 21:45 UTC, JlPOCTO commented on server/src/routes.js
> +    version + '/myInfo',
профиль все же немного более общее на мой взгляд понятие

2024-04-14 21:45 UTC, gr33n-m1ner commented on server/src/database/dbUsers.js
> +async function addUser(db, userID, userName, userNickname) {
Конкретно эта функция не работает с чатами, можно посмотреть на название и понять, что все это принадлежит юзеру
У чатов нет имени и логина
Если бы метод работал одновременно и с чатом и с пользователем, то да, префиксы нужны

2024-04-14 21:46 UTC, JlPOCTO commented on server/src/routes.js
> +    version + '/addMessage',
по той же причине не надо так делать

2024-04-14 21:51 UTC, JlPOCTO commented on server/src/database/dbUsers.js
> +async function addUser(db, userID, userName, userNickname) {
У тебя в подсказках высветится название переменной
Если ты где-то в другой части кода будешь писать лютую логику с чатами и пользователями, это позволит не перепутать, увидев подсказку в виде названия переменной

2024-04-14 22:00 UTC, gr33n-m1ner commented on server/src/database/dbUsers.js
> +async function addUser(db, userID, userName, userNickname) {
Я вообще не понял твой пример, когда это может иметь смысл
В другой части кода, где будет логика и чата и пользователя, очевидно нужны будут префиксы, чтобы названия id и id не пересекались
Но в методе addUser ты работаешь только с пользователем, нет никакой лютой логики, ты не запутаешься в методе из трех строк

2024-04-14 22:16 UTC, gr33n-m1ner commented on server/src/routes.js
> +    version + '/dialogs',
Если бы у тебя был просто id, то бага бы не произошло. Ты бы написал id, и тебе неважно какой конкретно id, так как у тебя по логике здесь если только 1 id

2024-04-14 22:38 UTC, gr33n-m1ner approved these changes

2024-04-14 22:39 UTC, merged