darkTheme, userInfo, Images added
JlPOCTO/YaHack pull request #7
Opened 2024-04-10 09:38 UTC by Anas-prv

2024-04-10 13:48 UTC, ElviraMinko submitted a review, later dismissed

2024-04-10 14:18 UTC, gr33n-m1ner requested changes
Нужно исправить баг со сменой темы

2024-04-10 21:24 UTC, gr33n-m1ner requested changes
В целом окей, если что я могу сам все это сделать и замержить

2024-04-10 21:24 UTC, gr33n-m1ner commented on Client/src/components/App/App.tsx
> +    console.log(nextTheme)
Лишнее

2024-04-10 21:24 UTC, gr33n-m1ner commented on Client/src/picture.jpg
Можешь создать отдельную папку для изображений? Я буду подгружать их вместе с отправлением страницы

2024-04-11 08:21 UTC, gr33n-m1ner approved these changes

2024-04-11 08:22 UTC, merged